# settings for curation concerns in a developemnt environment:
# derivatives_path contains thumbnails and web-friendly audio, and video files for playbock
derivatives_path: <%= File.join(Rails.root, 'tmp', 'derivatives') %>
# uploads_path stashes files uploaded via the browser before ingest to fedora
# on distributed architectures, uploads_path must be on a drive shared with the web server
uploads_path: <%= File.join(Rails.root, 'tmp', 'uploads') %>
# minter_path tracks the ID of the last-created object
minter_path: <%= File.join(Rails.root, 'tmp', 'minter-state') %>
resque_namespace: heliotrope-development
host: localhost:3000

# Should we create users automatically on first login?
# This supports convenient single sign-on account provisioning
create_user_on_login: false

keycard:
  database:
    adapter: sqlite
    database: db/keycard-development.sqlite3
    pool: 5
    timeout: 5000

checkpoint:
  database:
    adapter: sqlite
    database: db/checkpoint-development.sqlite3
    pool: 5
    timeout: 5000
